name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app
      
    - name: Build App
      run: xcodebuild -project "Uber.xcodeproj" -scheme "Uber" -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO
